---
- name: Test vmware_rest
  hosts: localhost
  gather_facts: False
  vars_files: vcenter_data_ansible.yml
  tasks:
    - name: Check all existing VM
      vmware.vmware_rest.vcenter_vm_info:
        vcenter_hostname: "{{ stf_vcenter_hostname }}"
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_validate_certs: False
      register: existing_vms
      until: existing_vms is not failed
    - debug:
        var: "existing_vms"
...
